language: en
pipeline:
- name: "SpacyNLP"
  model: "en_core_web_md"
- name: DucklingHTTPExtractor
  url: "http://localhost:8000"
  dimensions: ["time"]
  timezone: "Europe/Berlin"
  timeout : 3
- name: "SpacyEntityExtractor"
  dimensions: ["GPE"]
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.6
policies:
- name: RulePolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
