name: Automatic master merger
on:
  # whenever a change is pushed to a release branch,
  # open a pull request to merge changes down to master
  push:
    branches:
    - '[0-9]+.[0-9]+.x'

jobs:
  open_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@v2

      - name: Get branch name ✍️
        id: get-branch-name
        run: |
          GITHUB_BRANCH=${GITHUB_REF/refs\/heads\//}
          echo "::set-output name=release_branch::${GITHUB_BRANCH}"
          echo "::set-output name=new_branch::merge-${GITHUB_BRANCH}-${GITHUB_SHA:0:7}"

      - name: Create new branch 🐣
        uses: peterjgrainger/action-create-branch@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ steps.get-branch-name.outputs.new_branch }}

      - name: Open pull request ☄️
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ steps.get-branch-name.outputs.new_branch }}
          destination_branch: master
          pr_title: Merge ${{ steps.get-branch-name.outputs.release_branch }} into master
          pr_template: .github/PULL_REQUEST_AUTOMATIC_TEMPLATE.md
          pr_label: status:ready-to-merge
          pr_reviewer: ${{ github.event.pusher.name }}
