name: Automatic master merger
on:
  # whenever a change is pushed to a release branch,
  # open a pull request to merge changes down to master
  push:
    branches:
    - '[0-9]+.[0-9]+.x'

env:
  LABEL_TYPE: type:release-branch-port
  LABEL_STATUS: status:ready-to-merge

jobs:
  open_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@v2

      - name: Get branch name ✍️
        id: get-branch-name
        run: |
          GITHUB_BRANCH=${GITHUB_REF/refs\/heads\//}
          echo "::set-output name=release_branch::${GITHUB_BRANCH}"
          echo "::set-output name=new_branch::merge-${GITHUB_BRANCH}-${GITHUB_SHA:0:7}"

      - name: Create new branch 🐣
        uses: peterjgrainger/action-create-branch@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ steps.get-branch-name.outputs.new_branch }}

      - name: Get GitHub labels 🏷
        id: get-github-labels
        run: |
          git fetch --prune --unshallow --tags
          LATEST_RASA_X_MINOR=$(git tag --list | grep -E '^\d+\.\d+\.\d+$' | tail -n1 | sed -e 's/.\([0-9]\)*$/.0/g')
          LIST=$(git tag --list)
          echo $LIST
          echo "latest minor: ${LATEST_RASA_X_MINOR}"


          # bash doesn't support nested variable access
          CURRENT_RASA_X_MINOR=${GITHUB_REF/refs\/heads\//}
          CURRENT_RASA_X_MINOR=${CURRENT_RASA_X_MINOR/\.x/\.0}

          echo "Current minor: ${CURRENT_RASA_X_MINOR}"

          if [[ ${LATEST_RASA_X_MINOR} == ${CURRENT_RASA_X_MINOR} ]]
          then
            echo "::set-output name=labels::${LABEL_TYPE},${LABEL_STATUS}"
          else
            echo "::set-output name=labels::${LABEL_TYPE}"
          fi

      - name: Open pull request ☄️
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ steps.get-branch-name.outputs.new_branch }}
          destination_branch: master
          pr_title: Merge ${{ steps.get-branch-name.outputs.release_branch }} into master
          pr_template: .github/PULL_REQUEST_AUTOMATIC_TEMPLATE.md
          pr_label: ${{ steps.get-github-labels.outputs.labels }}
          pr_reviewer: ${{ github.event.pusher.name }}
