# This workflow will install Python dependencies, run chatbot tests

name: Chatbot tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry install
    - name: Test chatbot
      run: |
        poetry run rasa test --fail-on-prediction-errors -s data/test_stories.md 
